# SPDX-License-Identifier: LGPL-2.1-or-later
#
# This file is part of libcxlmi.
#
executable(
    'cxl-mctp',
    ['cxl-mctp.c'],
    dependencies: libcxlmi_dep,
    include_directories: [inc]
)

executable(
    'cxl-ioctl',
    ['cxl-ioctl.c'],
    dependencies: libcxlmi_dep,
    include_directories: [inc]
)

executable(
    'fmapi-mctp',
    ['fmapi-mctp.c'],
    dependencies: libcxlmi_dep,
    include_directories: [inc]
)

executable(
    'vcs-bind-mctp',
    ['vcs-bind-mctp.c'],
    dependencies: libcxlmi_dep,
    include_directories: [inc]
)

executable(
    'vcs-unbind-mctp',
    ['vcs-unbind-mctp.c'],
    dependencies: libcxlmi_dep,
    include_directories: [inc]
)

executable(
    'vcs-get-virtual-switch-info-mctp',
    ['vcs-get-virtual-switch-info-mctp.c'],
    dependencies: libcxlmi_dep,
    include_directories: [inc]
)
